[package]
name = "verified-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
sm = { path = "../sm" }

[workspace]

[package.metadata.verus.ide]
extra_args = "--extern=sm=../sm/target/debug/libsm.dylib"
